// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYlKKP5vcjckccG21M5xEYFfJx0aTGHgY',
    appId: '1:186076189944:web:4e2754d3b988f3c155170d',
    messagingSenderId: '186076189944',
    projectId: 'lastpush-977e8',
    authDomain: 'lastpush-977e8.firebaseapp.com',
    storageBucket: 'lastpush-977e8.appspot.com',
    measurementId: 'G-T8D6M886KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrfn0J0FIwY0V24_OEe7RAkCjml0Y6_Dc',
    appId: '1:186076189944:android:ddfb28c69872daed55170d',
    messagingSenderId: '186076189944',
    projectId: 'lastpush-977e8',
    storageBucket: 'lastpush-977e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT8W_IDF8NVGH1DsnoRmXRl8fw9xslMBU',
    appId: '1:186076189944:ios:c195846f502829f655170d',
    messagingSenderId: '186076189944',
    projectId: 'lastpush-977e8',
    storageBucket: 'lastpush-977e8.appspot.com',
    iosBundleId: 'com.example.lastPush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT8W_IDF8NVGH1DsnoRmXRl8fw9xslMBU',
    appId: '1:186076189944:ios:55114b4e435019eb55170d',
    messagingSenderId: '186076189944',
    projectId: 'lastpush-977e8',
    storageBucket: 'lastpush-977e8.appspot.com',
    iosBundleId: 'com.example.lastPush.RunnerTests',
  );
}
